### ISSUE TITLE
Feature request: note public fields as readonly in cargo docs.

### ISSUE THREAD

**Issue by maaku** [dtolnay/readonly#10]
This crate is cool, thank you! I've tested that indeed I can write the following in crate foo:

```rust
# crate/foo/src/lib.rs
#[readonly::make]
pub struct Data {
    #[readonly]
    pub name: String,
    ...
}
```

And then *within* that crate, I can do `data.foo = "blah".into()` or whatever, but from outside the crate attempting to set `data.foo` yields a `DerefMut` compilation error.  That's awesome, thank you.  However the generated docs still show:

```rust
pub struct Data {
    pub name: [String](https://doc.rust-lang.org/1.79.0/alloc/string/struct.String.html),
    /* private fields */
}
```

If would be nice if the docs somehow automatically showed the field as read-only. How, I'm not entirely sure. I see two obvious options:

A:
```rust
pub struct Data {
    #[readonly]
    pub name: [String](https://doc.rust-lang.org/1.79.0/alloc/string/struct.String.html),
    /* private fields */
}
```

B:
```rust
pub struct Data {
    pub name: [String](https://doc.rust-lang.org/1.79.0/alloc/string/struct.String.html), # read-only
    /* private fields */
}
```

Right now I'm forced to manually explain in the accompanying help text that the fields are read-only, which is less than ideal.

**Comment by dtolnay** [comment]
I think relying on the crate author to explain using handwritten docs the intended use of the type, including the fact that writing to the field is not supported, is my preferred approach.
