### ISSUE TITLE
Feature request: ability to call constructor from another module

### ISSUE THREAD

**Issue by whitefractal** [dtolnay/readonly#9]
Given 
```
#[readonly::make]
pub struct Foo {
    pub bar: i32
}
```

I want to be able to construct `Foo` objects outside the module which cannot then be modified; if I invoke `Foo {bar: 123}` from outside the module I get `field bar of struct mymodule::Foo is private`. Can work around this by defining `new`, but this doesn't have named arguments which are useful for non-trivial types.

**Comment by dtolnay** [comment]
I would prefer not to support this in this crate, but it would be reasonable for someone else to make a different implementation that can do this.
